/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alovera.glb 
Author: higgsas (https://sketchfab.com/higgsas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aloe-vera-plant-in-3d-printed-pot-247262acbc6e463f82c23564943edb1d
Title: Aloe Vera plant in 3d printed pot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Alovera(props) {
  const { nodes, materials } = useGLTF('/alovera.glb')
  const basilRef = useRef();
  
    // Animate continuous rotation like a spinning top (Beyblade)
    useFrame(() => {
      if (basilRef.current) {
        basilRef.current.rotation.z-= 0.005; // Adjust speed by changing 0.05
      }
    });
  return (
    <group  {...props} dispose={null}>
      <group position={[0,0,-0.20]} rotation={[-Math.PI/2,0,0]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.material} />
      </group>
      <group rotation={[-Math.PI/2,0,0]}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.leaf} position={[0.014, 0.191, -0.008]} rotation={[-2.039, -1.51, -2.033]} scale={0.008} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.leaf} position={[-0.022, 0.184, 0.007]} rotation={[-2.589, 0.958, 2.675]} scale={0.01} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.leaf} position={[-0.001, 0.182, 0.026]} rotation={[-2.733, 0.134, 3.092]} scale={0.008} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.leaf} position={[0.028, 0.179, 0.016]} rotation={[-2.425, -0.673, -2.664]} scale={0.004} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.leaf} position={[0.013, 0.19, -0.02]} rotation={[-0.026, -0.647, -0.02]} scale={0.013} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.leaf} position={[-0.004, 0.191, -0.002]} rotation={[3.125, 0.931, 3.142]} scale={0.008} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.leaf} position={[-0.001, 0.188, -0.028]} rotation={[-0.124, 0.259, 0.012]} scale={0.012} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.leaf} position={[-0.019, 0.186, -0.018]} rotation={[-0.387, 1.145, 0.338]} scale={0.012} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.leaf} position={[-0.005, 0.191, -0.016]} rotation={[-0.018, 0.825, 0.032]} scale={0.01} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.leaf} position={[0.015, 0.186, 0.016]} rotation={[-2.837, -0.418, -3.023]} scale={0.011} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.leaf} position={[0.035, 0.184, -0.001]} rotation={[-2.112, -1.209, -2.127]} scale={0.009} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.leaf} position={[0.03, 0.181, -0.03]} rotation={[-0.685, -0.754, -0.535]} scale={0.006} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.leaf} position={[0.008, 0.192, -0.002]} rotation={[3.083, -0.591, 3.106]} scale={0.004} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.leaf} position={[-0.013, 0.189, -0.005]} rotation={[-2.681, 1.404, 2.698]} scale={0.013} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.leaf} position={[-0.006, 0.188, 0.011]} rotation={[-2.988, 0.472, 3.064]} scale={0.013} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.leaf} position={[0.012, 0.185, -0.035]} rotation={[-0.225, -0.309, -0.042]} scale={0.01} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.leaf} position={[-0.015, 0.183, -0.035]} rotation={[-0.395, 0.592, 0.229]} scale={0.008} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.leaf} position={[-0.031, 0.18, -0.009]} rotation={[-1.5, 1.034, 1.507]} scale={0.005} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.leaf} position={[0.005, 0.19, 0.006]} rotation={[-3.139, -0.107, -3.114]} scale={0.012} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.leaf} position={[0.005, 0.191, -0.017]} rotation={[-0.031, -0.159, 0.007]} scale={0.006} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.leaf} position={[0.02, 0.189, 0.002]} rotation={[-2.971, -1.018, -2.983]} scale={0.013} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.leaf} position={[0.026, 0.187, -0.016]} rotation={[-0.368, -1.216, -0.333]} scale={0.013} />
    </group>
    </group>
  )
}

useGLTF.preload('/alovera.glb')
export default Alovera;
