/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Turmeric.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Turmeric(props) {
  const { nodes, materials } = useGLTF('/Turmeric.glb')
  const basilRef=useRef();
  useFrame(()=>{
    if(basilRef.current){
      basilRef.current.rotation.z-=0.2;
    }
  })
  return (
    <group {...props} dispose={null}>
      <group scale={1.5}>
        <group position={[0,0,0]} rotation={[-Math.PI/2,0,0]} scale={[1,1,1]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} castShadow receiveShadow />
    </group>
    </group>
    </group>
  )
}

useGLTF.preload('/Turmeric.glb')
export default Turmeric;

